"""agregar tabla config_app

Revision ID: 14ba9cefb74e
Revises: b2c3d4e5f6a7
Create Date: 2026-04-11 22:07:22.338643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba9cefb74e'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_primary', sa.String(length=7), nullable=False),
    sa.Column('color_accent', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_local_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_visitante_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_fases', ['fase_id'], ['id'])

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_partidos', ['partido_id'], ['id'])

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'funciones', ['funcion_id'], ['id'])

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('config_app')
    # ### end Alembic commands ###
