"""banners publicitarios

Revision ID: 2aed07616e42
Revises: b6b9d6cf4fd4
Create Date: 2026-04-12 22:40:02.687425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aed07616e42'
down_revision = 'b6b9d6cf4fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.Column('url_destino', sa.String(length=500), nullable=True),
    sa.Column('posicion', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_grupo_invitaciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['invitado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_grupos', ['grupo_id'], ['id'])

    with op.batch_alter_table('prode_grupo_miembros', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_grupos', ['grupo_id'], ['id'])

    with op.batch_alter_table('prode_grupos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['creador_id'], ['id'])

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_local_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_visitante_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_fases', ['fase_id'], ['id'])

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_partidos', ['partido_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'funciones', ['funcion_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_grupos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_grupo_miembros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_grupo_invitaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('banners')
    # ### end Alembic commands ###
