"""initial

Revision ID: 597932a6672d
Revises: 
Create Date: 2026-04-09 22:42:28.998982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597932a6672d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('es_menu', sa.Boolean(), nullable=True),
    sa.Column('ubicacion_menu', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('prode_torneos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('inscripcion_abierta', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('auth_origen', sa.String(length=10), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('prode_config_puntaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('resultado_exacto', sa.Integer(), nullable=True),
    sa.Column('resultado_parcial', sa.Integer(), nullable=True),
    sa.Column('resultado_errado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['prode_torneos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torneo_id')
    )
    op.create_table('prode_equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('grupo', sa.String(length=10), nullable=True),
    sa.Column('escudo_url', sa.String(length=255), nullable=True),
    sa.Column('codigo_iso', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['prode_torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prode_fases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['prode_torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prode_inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torneo_id'], ['prode_torneos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'torneo_id', name='uq_prode_inscripcion')
    )
    op.create_table('rol_funcion',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('funcion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcion_id'], ['funciones.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'funcion_id')
    )
    op.create_table('sesiones_activas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('primer_acceso', sa.DateTime(), nullable=False),
    sa.Column('ultimo_visto', sa.DateTime(), nullable=False),
    sa.Column('invalidada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesiones_activas_session_token'), ['session_token'], unique=True)

    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('prode_partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fase_id', sa.Integer(), nullable=False),
    sa.Column('equipo_local_id', sa.Integer(), nullable=False),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['prode_equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['prode_equipos.id'], ),
    sa.ForeignKeyConstraint(['fase_id'], ['prode_fases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prode_pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['prode_partidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'partido_id', name='uq_prode_usuario_partido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prode_pronosticos')
    op.drop_table('prode_partidos')
    op.drop_table('usuario_rol')
    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesiones_activas_session_token'))

    op.drop_table('sesiones_activas')
    op.drop_table('rol_funcion')
    op.drop_table('prode_inscripciones')
    op.drop_table('prode_fases')
    op.drop_table('prode_equipos')
    op.drop_table('prode_config_puntaje')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('prode_torneos')
    op.drop_table('funciones')
    # ### end Alembic commands ###
