"""grupos privados entre usuarios

Revision ID: b6b9d6cf4fd4
Revises: 14ba9cefb74e
Create Date: 2026-04-11 22:54:08.701575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b9d6cf4fd4'
down_revision = '14ba9cefb74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prode_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('prode_grupo_invitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('invitado_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['prode_grupos.id'], ),
    sa.ForeignKeyConstraint(['invitado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('prode_grupo_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['prode_grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'usuario_id', name='uq_grupo_miembro')
    )
    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_torneos', ['torneo_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_local_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_equipos', ['equipo_visitante_id'], ['id'])
        batch_op.create_foreign_key(None, 'prode_fases', ['fase_id'], ['id'])

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'prode_partidos', ['partido_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'funciones', ['funcion_id'], ['id'])

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sesiones_activas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rol_funcion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_pronosticos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_partidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_fases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_equipos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prode_config_puntaje', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('prode_grupo_miembros')
    op.drop_table('prode_grupo_invitaciones')
    op.drop_table('prode_grupos')
    # ### end Alembic commands ###
